name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install black ruff mypy pytest pytest-asyncio pytest-timeout respx pydantic pydantic-settings requests
    - name: Format check
      run: black --check mcp_simple_tool tests
    - name: Lint
      run: |
        ruff check mcp_simple_tool
        mypy mcp_simple_tool
    - name: Test
      run: pytest -q 